# Generated by Django 4.1.6 on 2023-02-15 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Records",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "authorKorean",
                    models.CharField(default="", max_length=100, null=True),
                ),
                (
                    "authorEnglish",
                    models.CharField(default="", max_length=100, null=True),
                ),
                ("workTitle", models.CharField(default="", max_length=100, null=True)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Fictions", "Fictions"),
                            ("Poems", "Poems"),
                            ("Essays", "Essays"),
                            ("Plays", "Plays"),
                            ("Childrens", "Childrens"),
                            ("Classic_General", "Classic_General"),
                            ("Classic_Poem", "Classic_Poem"),
                            ("Classic_History", "Classic_History"),
                            ("Classic_Flok Tale", "Classic_Flok Tale"),
                            ("Classic_Fiction", "Classic_Fiction"),
                            ("Misc", "Misc"),
                        ],
                        default=("Poems", "Poems"),
                        max_length=200,
                        null=True,
                    ),
                ),
                ("translator", models.CharField(default="", max_length=100, null=True)),
                (
                    "sourceTitle",
                    models.CharField(default="", max_length=100, null=True),
                ),
                ("publisher", models.CharField(default="", max_length=100, null=True)),
                (
                    "Year",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 2, 15, 8, 7, 44, 178961, tzinfo=datetime.timezone.utc
                        ),
                        null=True,
                    ),
                ),
            ],
        ),
    ]
