# Generated by Django 4.1.6 on 2023-02-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchtool", "0002_record_delete_records"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="Year",
        ),
        migrations.AddField(
            model_name="record",
            name="yearCreated",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
