# Generated by Django 4.1.6 on 2023-02-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchtool", "0003_remove_record_year_record_yearcreated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="authorEnglish",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="authorKorean",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="genre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Fictions", "Fictions"),
                    ("Poems", "Poems"),
                    ("Essays", "Essays"),
                    ("Plays", "Plays"),
                    ("Childrens", "Childrens"),
                    ("Classic_General", "Classic_General"),
                    ("Classic_Poem", "Classic_Poem"),
                    ("Classic_History", "Classic_History"),
                    ("Classic_Flok Tale", "Classic_Flok Tale"),
                    ("Classic_Fiction", "Classic_Fiction"),
                    ("Misc", "Misc"),
                ],
                default=("Poems", "Poems"),
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="publisher",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="sourceTitle",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="translator",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="workTitle",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="yearCreated",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
