# Generated by Django 4.1.7 on 2023-03-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchtool', '0004_alter_record_authorenglish_alter_record_authorkorean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='authorEnglish2',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
