# Generated by Django 4.1.7 on 2023-03-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchtool', '0005_record_authorenglish2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='yearCreated',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
