# Generated by Django 4.1.7 on 2023-05-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchtool', '0011_addrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='workTitleKorean',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
