# Generated by Django 4.1.7 on 2023-11-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("searchtool", "0014_alter_record_genre"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userName", models.CharField(max_length=100)),
                ("userPassword", models.CharField(max_length=100)),
                (
                    "userEmail",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="record",
            name="genre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Fiction", "Fiction"),
                    ("Poetry", "Poetry"),
                    ("Essay", "Essay"),
                    ("Play", "Play"),
                    ("Graphic Novel", "Graphic Novel"),
                    ("Children’s Literature", "Children’s Literature"),
                    ("Classic_General", "Classic_General"),
                    ("Classic_Poetry", "Classic_Poetry"),
                    ("Classic_History", "Classic_History"),
                    ("Classic_Folk Tale", "Classic_Folk Tale"),
                    ("Classic_Fiction", "Classic_Fiction"),
                    ("Misc", "Misc"),
                ],
                default=("Poetry", "Poetry"),
                max_length=200,
                null=True,
            ),
        ),
    ]
